[package]
name ="demo"
version ="0.1.0"
authors = ["Rico"]
edition ="2021"

[dependencies]
commutil = { path = "./commutil" }
rand = "0.8.3"


[[bin]]
name = "demo"
path = "src/demo.rs"

[workspace]
members = [
    "commutil",
]
